version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: taskmgmt_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: taskmgmt_backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/task_mgmt
      - JWT_SECRET=dev_secret_change_me
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: taskmgmt_frontend
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo_data:
